### PR TITLE
Have impinj custom parameters as normal defined parameter in llrp_proto

### PR DESCRIPTION
**Pull request by fviard**
...instead of having the parameters values hard coded in the rospec dict.

In  my opinion it is a cleanup, but the main goal was to fix issues when using the "--debug" option and the impinj custom features. I had either an exception or the custom parameters were just not displayed in the debug "xml".

### CODE REVIEW

**Comment by thijmenketel** [comment]
Seems a little redundant to create an encoding function for every parameter as they are just custom parameters, now you have three completely identical encoding functions. The separate structs are clear and might improve readability but creating a separate function for each seems to me to make the code less clear.

**Comment by thijmenketel** [comment]
Furthermore, adding the searchmode parameter to the C1G2InventoryCommand might make sllurp incompatible with non-Impinj readers.

**Comment by fviard** [comment]
> Furthermore, adding the searchmode parameter permanently to the C1G2InventoryCommand might make sllurp incompatible with non-Impinj readers.

I don't think that this will be an issue with the patch, and probably not more than before.
Because the field will only be added if the relevant entry is set in the rospec dict, and that entry will only be set if "impinj_search_mode" is used.

> Seems a little redundant to create an encoding function for every parameter as they are just custom parameters, now you have three completely identical encoding functions. The separate structs are clear and might improve readability but creating a separate function for each seems to me to make the code less clear.

Even if they are custom parameters, that doesn't mean that they are not stable and specified.
The first idea of the patch, is to remove the "encoding" specific info for the custom params from the rospec logic construction function.
 
Regarding the kind duplicated struct, my idea is to be generic for any more custom parameter that could be added and not do anything specific for these ones that "by chance" are similar. Each custom parameter could in theory encode its payload value differently even if here it is the same thing.

As discussed before in  another, probably the global thing can be refactored, having a specific encoding function for custom parameters and messages, and maybe a dedicated msg_struct for parameters.  But i wanted to do just a simple change that would fix my issues, and not a refactor like creating encoding functions with different prototype for this special case for example. That is certainly just a first step, but should be a already a little bit better than before in my opinion.

**Comment by thijmenketel** [comment]
> I don't think that this will be an issue with the patch, and probably not more than before.
Because the field will only be added if the relevant entry is set in the rospec dict, and that entry will only be set if "impinj_search_mode" is used.

Sorry about that one, didn't see the if statement.

> As discussed before for another issue, probably the global thing can be refactored, having a specific encoding function for custom parameters and messages, and maybe a dedicated msg_struct for parameters. But i wanted to do just a simple change that would fix my issues, and not a refactor like creating encoding functions with different prototype for this special case for example. That is certainly just a first step, but should be a already a little bit better than before in my opinion.

I concur with the separate message structs, makes it very readable. And you're right that each custom parameter can be different (which can be checked [here](https://support.impinj.com/hc/article_attachments/360000031199/Impinj_Octane_LLRP.pdf)), however as the ImpinjTagReportContentSelector has identical (current implementation) payloads it is quite redundant to copy the encoding function (which is also implemented by encode_CustomParameter) three times. It gives the suggestion that no matter what, no function can be reused which doesn't make sense.

**Comment by ransford** [comment]
This patch looks reasonable to me.  Do you mind making the test suite pass, @fviard?

If I understand correctly, your primary goal was to be able to print messages that contained Impinj custom parameters.  You could add a unit test for this specific case.

sllurp has a huge pile of encoding and decoding functions.  It started as a fork of another library, and as I gradually extended LLRP support, I just kept adding functions. :-)

**Comment by fviard** [comment]
@ransford Here it is, hacky fix so the test suite is happy enough.

It took me a little bit of time, but at least I start to have an understanding of the logic of the thing :-)
I have a few other things to submit soon. It can be a little bit rough but should improve a little bit.
But there is not a lot of chance that I have time to improve the unit testing as i'm quite running after time and have still a lot to do for what was my intended usage.

I have a big work in progress, that I hope I will be able to share soon as a branch.
I don't know if it will go in a direction that you will like.
I got ride of twisted dependency by simply having a python threaded loop that should work the same for python2 and python3.

So, "Deferred" were replaced by simple callbacks.
I think that it simplify a lot and allows to solve some things that were hacky like when twisted "task" had to be sued.

This would also allow a step 2 for this work, that would be to transform the main thing more into a library than having the handle_message state loop that kind of force to have a single "inventory" scheme of operation.

**Comment by ransford** [comment]
Thanks for this.  Your work in progress sounds exciting!

**Pull request merged**
