### PR TITLE
Support for Harting RFID devices

### PR DESCRIPTION
**Pull request by troelsy**
The company I work for uses a Harting RFR300 RFID reader, but the current implementation of sllurp is not compatible. I have compared the sample code from Harting with sllurp and found some missing features of the compliances specification.

With my additions, the reader from Harting is fully compatible with sllurp, but I had to make some major changes to the state machine. All changes are, of course, fully compliant with the LLRP specification. Besides the state machine, I added some new messages and responds.

Most noteworthy addition to the code is the change in "Message_struct". The Message_struct had all messages and their corresponding codes, but these are only unique across TLV-encoded messages. Some TV-encoded messages have colliding codes with TLV-encoded messages and it is therefor necessary to have to different dictionaries for TV-encoded and TLV-encoded messages.

The new messages added are:
- SET_READER_CONFIG
- SET_READER_CONFIG_RESPONSE
- START_ROSPEC
- START_ROSPEC_RESPONSE
- ENABLE_EVENTS_AND_REPORTS
- GET_READER_CONFIG
- GET_READER_CONFIG_RESPONSE

GET_READER_CONFIG_RESPONSE contains a lot of data structures, all of which is implemented, but GET_READER_CONFIG_RESPONSE is not used anywhere in the code, since I mostly used it for debugging.

### CODE REVIEW

**Comment by troelsy** [comment]
It fails because I purposefully changed Message_struct

**Comment by ransford** [comment]
Hi @troelsy, I'll have time to review this weekend.  Thank you for this -- looks like a great changeset!

**Comment by ransford** [comment]
Tests in `sllurp.test` were easy to fix, but unfortunately this PR breaks `bin/inventory` on my Impinj Speedway Revolution R220 reader (tested like `bin/inventory -d my.reader`):
```
2016-09-04 15:45:51,524 sllurp.llrp: DEBUG: LLRPMessage received in state 14: <READER_EVENT_NOTIFICATION>
       	<Ver>1</Ver>
       	<Type>63</Type>
       	<ID>1800019388</ID>
       	<ReaderEventNotificationData>
       		<AntennaEvent>
       			<EventType>Connected</EventType>
       			<AntennaID>1</AntennaID>
       		</AntennaEvent>
       	</ReaderEventNotificationData>
</READER_EVENT_NOTIFICATION>
2016-09-04 15:45:51,524 sllurp.llrp: DEBUG: starting message callbacks for READER_EVENT_NOTIFICATION
2016-09-04 15:45:51,524 sllurp.llrp: DEBUG: done with message callbacks for READER_EVENT_NOTIFICATION
2016-09-04 15:45:51,524 sllurp.llrp: DEBUG: in handleMessage(READER_EVENT_NOTIFICATION), there are 0 Deferreds
2016-09-04 15:45:51,524 sllurp.llrp: ERROR: unexpected response READER_EVENT_NOTIFICATION when starting ROSpec
2016-09-04 15:45:51,525 sllurp.llrp: ERROR: failed to parse status from READER_EVENT_NOTIFICATION
Traceback (most recent call last):
  File "sllurp/llrp.py", line 113, in isSuccess
    ['ConnectionAttemptEvent']['Status'] == 'Success'
KeyError: 'ConnectionAttemptEvent'
Unhandled Error
Traceback (most recent call last):
  File "/Users/ben/vc/sllurp/venv/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/ben/vc/sllurp/venv/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/ben/vc/sllurp/venv/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/ben/vc/sllurp/venv/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/ben/vc/sllurp/venv/lib/python2.7/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/ben/vc/sllurp/venv/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/Users/ben/vc/sllurp/venv/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/ben/vc/sllurp/venv/lib/python2.7/site-packages/twisted/protocols/basic.py", line 578, in dataReceived
    why = self.rawDataReceived(data)
  File "sllurp/llrp.py", line 586, in rawDataReceived
    self.handleMessage(lmsg)
  File "sllurp/llrp.py", line 486, in handleMessage
    status = lmsg.msgdict[msgName]['LLRPStatus']['StatusCode']
exceptions.KeyError: 'LLRPStatus'
```

**Comment by ransford** [comment]
Is this still worth working on?

**Comment by troelsy** [comment]
I'm sorry, I don't work for the company anymore, so I don't have access to the device for debugging. I still think it is worth merging, though; since I only implemented specs described in the requirement specification and others may find that useful.

For the traceback you sent, I would try to print out lmsg.msgdict[msgName] to see what it actually contains.

**Pull request closed without merging**
