### PR TITLE
fix TX power configuration compatibility with Zebra FX9600 reader

### PR DESCRIPTION
**Pull request by avasygn**
A PR to fix the TX power configuration when max power is set by the user.

More details here: #141

### CODE REVIEW

**Comment by ransford** [comment]
I made a few changes so that we always grab the maximum power when the user asks for tx_power=0.

Unfortunately, this means that it's hard to actually select the _first_ item in the tx_power list... when you mean index 0 (the first item), you get the maximum power! Fixing this blemish will require a minor version bump.

**Comment by ransford** [comment]
I'm inclined to merge this. Any objections?

Thanks again for this PR and for raising this issue!

**Comment by avasygn** [comment]
Sounds good to me. Thank you for adding tests (especially for the Zebra). I will try this fix with my Zebra reader and I let you now.

**Comment by avasygn** [comment]
> Unfortunately, this means that it's hard to actually select the _first_ item in the tx_power list... when you mean index 0 (the first item), you get the maximum power! Fixing this blemish will require a minor version bump.

Maybe a command entry point to get the reader capabilities could be very useful (like inventory and access)

```
sllurp capabilities 192.168.1.5 # ask and display the reader capabilities
```

I can create an issue for that. What do you think about that?

Otherwise, I have understood the previous zebra issue better. The function llrp.parsePowerTable() create a power table list according to the number of `TransmitPowerLevelTableEntry` + 1. Then it fills the list with each `TransmitPowerLevelTableEntry` value according to its index.

For Impinj speedway reader, index starts from 1 to N, and with N=4  (there are 4 TransmitPowerLevelTableEntry)
power_table = [0, 10.0, 10.25, 10.5, 10.75] ->  there are 5 items in this list
```
sllurp inventory 192.168.1.5 -X 0 # inventory with max tx_power -> works
sllurp inventory 192.168.1.5 -X 4 # inventory with tx_power=10.75dBm (max power as well) -> works
```

For Zebra FX9600 reader, index starts from 0 to N, and with N=4  (there are 5 TransmitPowerLevelTableEntry)
power_table = [10.0, 10.25, 10.5, 10.75, 11.0, 0] ->  there are 6 items in this list
```
sllurp inventory 192.168.1.5 -X 0 # inventory with max tx_power -> works
sllurp inventory 192.168.1.5 -X 5 # fails because reader does not know index 5
```

Thus, Zebra reader does not understand the last index of the power_table.

Actually, this is not a big issue, because user does not know all the power table. But it could lead to an error if a developer uses the power_table and parses all of it.

Thus, I suggest few ways to solve it:
- tx_power_table = [0] * (N + 1) instead of tx_power_table = [0] * (len(bandtbl) + 1)   
   with N = index of the last TransmitPowerLevelTableEntry
- if the user asks an index for which the value is equal to 0 then the function llrp.get_tx_power() returns the index of the max power which should be N

What do you think about that? Which way seems better? Do you want to suggest other solution?

**Comment by ransford** [comment]
+1 to the `sllurp capabilities <addr>` idea.

I'm not sure I understand your interpretation of the problem, but I think the best approach is to preserve the user's intention; if they ask for tx_power 0, they want the maximum power. I think that means the second one of your suggestions feels right...

**Comment by ransford** [comment]
Oh, and thanks for working on this!

**Comment by avasygn** [comment]
> +1 to the sllurp capabilities <addr> idea.

I did it: #150

**Pull request closed without merging**
