### PR TITLE
Add the -c command line option.

### PR DESCRIPTION
**Pull request by jettan**
This makes it able to specify what content to write to the usrbank.
Also, the read data format has been fixed. (in an additional print).

### CODE REVIEW

**Comment by ransford** [comment]
Is this PR still necessary?

**Comment by jettan** [comment]
The changing accessSpecs ability has been added to my fork of sllurp.
https://github.com/jettan/sllurp But it is not entirely completed yet as it
has sone flaws with the reader timings. We were planning to write a mail
with our milestone to all of you. Please expect it soon.

- Jethro

**Comment by jettan** [comment]
Oops  I thought you meant public repo instead of pull request. Might as
well scrape it and I will make a better one coming from the repo I just
mentioned.

**Comment by ransford** [comment]
Closing per @jettan's comment above.

**Pull request closed without merging**
