### PR TITLE
Rework to remove twisted dependency and to improve performances

### PR DESCRIPTION
**Pull request by fviard**
The main goal of this PR is to remove the dependency on Twisted.
On the way to this objective, rework was also done to improve inventory read performances.

Warning: Breaking changes!
The sllurp python "llrp.py" api was highly changed and so third party applications using it would have to also be reworked in order to be compatible with this new version.

### CODE REVIEW

**Comment by thijmenketel** [comment]
Related issue: #106

**Comment by ransford** [comment]
Cool, this is great. I'll take a look shortly. (The minor merge conflicts are due to a simplification I just merged; I can fix them.)

**Comment by ransford** [comment]
@fviard could you say a little more about "third party applications using it would have to also be reworked"?

**Comment by ransford** [comment]
I resolved the merge conflicts in a new branch `fviard-develop_untwisted` since I couldn't push directly into your branch. Maybe you could rebase your branch on that one?

This PR introduces a pretty major change, as you know. After a quick review, the code looks OK to me, but I'd like to try updating an application that depends on sllurp. I have an application that is based on Twisted and runs sllurp using the reactor -- i.e., it adds an `LLRPClientFactory` to its reactor that controls the main application loop. Since you removed `LLRPClientFactory`, I'm not sure how I should refactor my application. (The main README in this package still mentions `LLRPClientFactory` and needs an update as part of this PR.)

Also: could you include some testing instructions/suggestions in this PR?

**Comment by fviard** [comment]
@fviard could you say a little more about "third party applications using it would have to also be reworked"?
As you can see, client app will not use twisted anymore, and to use ReaderConfig and ReaderClient instead.

I forgot to update the README, you are right, I will fix that.
In the mean time, you can have a look at the last commits on the "tornado" example, or on the inventory.py, differences should be easy to understand I hope.

**Comment by fviard** [comment]
@ransford Are you sure that you can't push to my branch? with the PR i see enabled the " Allow edits from maintainers." option.

**Comment by ransford** [comment]
You're right, I just pushed to your branch (as you probably noticed).

**Comment by fviard** [comment]
@ransford I have fixed the README. That should be all good now.

**Comment by ransford** [comment]
Sorry, I'll get to this soon, I promise!

**Comment by fviard** [comment]
@ransford Ping :-)
I merged the latest changes from develop to my branch.
My life will become a lot easier once you will be able to merge the PR.

**Comment by avasygn** [comment]
Hello @fviard,
Your work seems very interesting. I have few questions:
- Is your development stable ? 
- what about performance improvements ? How many inventory/second do you get?
Thanks !

**Comment by fviard** [comment]
@avasygn I think that it is quite stable and reliable so far.
Normally even more than MASTER of Sllurp.
For the speed, I have a quite powerful laptop but I can get to the maximum possible speed of the reader I think.
Way faster than MASTER and at least a similar speed as the official impinj client.
You can look at the issue #106 for some numbers.
The important point is that the maximum speed of the reader depend of the reader settings that you are using.

**Comment by avasygn** [comment]
Hello @fviard,

I switched to your branch for my application. It works well.

Thank you

**Comment by ransford** [comment]
This is good work and it sounds like other people are getting some value out of it, but unfortunately it seems to be blocked on me, which isn't fair.

I have a few questions that will help unblock it!

1. Have you given any thought to helping clients reconnect (#138)?

2. Is this refactor likely to make installation of sllurp on Windows *easier* or *harder*, or no different? (Right now it's a pain to install on Windows because Twisted wants parts of itself to be compiled to native targets.)

3. Is there anything that definitely doesn't work anymore? I'm pretty sure 95%+ of sllurp users just write a thin wrapper around tag inventory, so as long as inventory works reliably, it's OK if some things break. After all, this project's major version number is still 0, so breaking changes are to be expected.

4. If someone wants to run a webserver (for example) in their application, it's easy to implement in Twisted by adding another "protocol" to the reactor. I've seen sllurp used this way many times. Is this kind of thing still easy? If not, can you add README text explaining how to do it?

i think some of these could be addressed via README modifications. Thank you for doing this work, and I hope we can get this merged soon.

**Comment by fviard** [comment]
Sorry for the long delay of the reply:

1) Normally, the reconnect "option" should work as well as for the twisted version. The same as for twisted, depending of the network setup, the broken connection might be detected only after linux network stack timeout. Also, retries are immediate, so if the network is down for a long time, we will not retry later. But anyway, from the callling script it is easy to be informed when we are disconnected and so act depending on the client needs.
2) It can only be easier to install/use on windows as we are just using python base libraries and less external libraries. But I think that I have not tested on windows, so maybe there could easily still be a few bugs in the code related to windows like "path separator" issues and co.
3) So far as I know, it is stable, works well and provides at least the same features as the twisted version. Also, it has the first abstractions to have tag specific read/write/ops done easier and cleaner, by users as I see that being requested a lot here. 
4) It is a lot way easier to integrate into any webserver. Btw, I have also, updated the tornado example in the code, so you can try it as is like you used to.

**Comment by avasygn** [comment]
Hello,
I am using this untwisted branch so please find additional information:
- I designed a sllurp and pyqt5 based application to perform memory access in TAGs (connect/disconnect, set IP addres, set TX power, inventory, access... all work fine)
- The previous application works on Linux and Windows and as single-windows-exe (pyinstaller and cx_freeze) as well
- I designed few tornado example based web applications and they work well
- All my applications are compatible with following readers:
   - Impinj reader (R420, R220)
   - Zebra FX9600
   - Do not work with kathrein reader (RRU 4400) and I have not investigated yet
- I no longer use twisted version because:
   - Compatibility with pyqt5 is restrictive (both pyqt and twisted reactor run on event loop)
   - Hard to package twisted in a single exe file (it does not work with pyinstaller, it works with cx_freeze after tricks because the zope dependency required by twisted is not easily to package)

Maybe, I did not optimize my code well to use the twisted version. But according to my needs and to deploy application quickly, untwisted version seems to be easier to use and to integrate with pyqt5.

**Comment by fviard** [comment]
Fixed with the dedicated branch "fviard-develop-v2".
https://github.com/ransford/sllurp/tree/fviard-develop-v2

**Pull request closed without merging**
