### PR TITLE
Impinj Low Level Extension support (discussed in issue #31)

### PR DESCRIPTION
**Pull request by thijmenketel**
As discussed in (closed) issue #31, there is some interest in using the impinj low level reader extensions. 

In this pull I implemented some of these, specifically the phase angle readings, (impinj) peak rssi readings and the rf doppler frequency readings. The inventory file in sllurp/verb/ can be edited to choose which extension is enabled. I've tested these additions with an R420 and I have had no problems. 

One thing has to be noted though. By the nature of the RFID protocol, the readers need to change their channel every so often. This hopping will interfere with the phase angle and doppler frequency and does need compensation.

Also, my commit history isn't that clean but I'm not that proficient with git unfortunately to fix it.

### CODE REVIEW

**Comment by thijmenketel** [comment]
I think the test fail due to the extension of the rospec, which isn't tested for.

**Comment by ransford** [comment]
At first glance, this looks great!

What steps do you recommend to test this code against my own Impinj reader?

**Comment by thijmenketel** [comment]
I think all the additions work directly by just using the run steps from the readme of sllurp. I run the inventory by using this script: 
```
python3 -m venv .venv &&
source .venv/bin/activate &&
pip3 install . &&
sllurp inventory -n 1 -s 2 -P 32 -M WISP5 --impinj-search-mode 2 \<reader-ip\>
deactivate &&
rm -rf .venv
```

It might also be smart to add an argument like the impinj-search-mode to prevent this code from being incompatible with readers that do not support the extensions.

**Comment by thijmenketel** [comment]
Just added a cli option to specifically enable/disable the extensions. This means that the code has to be run as follows: 
```
python3 -m venv .venv &&
source .venv/bin/activate &&
pip3 install . &&
sllurp inventory -n 1 -s 2 -P 32 -M WISP5 --impinj-search-mode 2 <reader-ip>
deactivate &&
rm -rf .venv
```

**Pull request merged**
