### PR TITLE
Fixed frequency support (for Impinj readers in supported regions)

### PR DESCRIPTION
**Pull request by thijmenketel**
I was looking into making my reader use a single frequency to counteract the phase angle shift offsets caused by the frequency hopping. However after initial implementation I found that FCC regulations (which my reader unfortunately is) don't allow fixed frequencies. As I couldn't change my readers region (although I'm in europe, reader's a hand me down from a US university) I thought maybe some other people could use the fixed frequency settings.

As I'm not able to test if the fixed frequency really works (I only get an error that I'm not in the correct region), maybe @fviard can try it on his ETSI reader.

I implemented the ImpinjFixedFrequencyList parameter from the Octane LLRP document from Impinj (page 119).

### CODE REVIEW

**Comment by thijmenketel** [comment]
@ransford I'm just curious if there's even interest in this? I confirmed that this works through the Rospec on the R420 I've available.

**Comment by thijmenketel** [comment]
Thanks for the reply!

> This thing provides a feature that is kind of the opposite of its name:
> In ETSI region we can not select a "hop table", so with the raw llrp spec, we can only choose one single frequency.
> This custom option allows to select multiple (or all frequencies), and so still have the reader switch automatically between the selected frequencies within a single AISpec.

Indeed that's what I got from the documentation. The current implementation only applies to the inventory command and is hard-coded to option 2 (from the octane guide) when enabled. This works fine I think but might be extended in the future for a better implementation.

**Comment by ransford** [comment]
Thanks, this is good!

**Comment by fviard** [comment]
@thijmenketel Something that you could be interested in:
In my branch, I have reworked a little bit that:
https://github.com/fviard/sllurp/commit/d353818886a67fc8ecf1d4131044c849a7155c34

So, now, in the cli, the "fixed_frequency" custom parameter was removed, and replaced by:
"-f 1,2" and "--hoptable-id 2".

With "-f", you set the channel to use, and if it is more than one or that you put "0", then, the custom extension for fixed_frequencies will be tried to be used.
If you use "0", it means "all", ie tells the impinj to choose all fixed frequencies for a region (mode 1).

With hoptable-id, as you can deduct from its name, it set the hoptable if you need.

From the API side, you can see in the inventory.py the example of the "frequencies" dict to use.
I think that it is not optimal, and that and other configs should probably be replaced by real "python" objects at some point. But that works right for the moment.

**Comment by thijmenketel** [comment]
That looks like a more streamlined solution indeed. I can't test it however haha, running an older FCC version of the r420 so the hoptable and frequencies are hardcoded.

**Comment by fviard** [comment]
@thijmenketel Any reason why you have not updated it? It is very easy to update and you can also easily downgrade later if needed.
The behavior of the reader can have changed a lot since your version i think.

**Comment by thijmenketel** [comment]
@fviard I am actually running one of the latest firmware version but the reader doesn't allow me to change the operating region from FCC to ETSI for some reason. I think it's because the r420 I'm using is an older one which does support latest octane version but not region changing.

**Pull request merged**
